sudo: required
services:
  - docker

before_install:
  - docker build -t raymondyux/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raymondyux/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  environment: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-060795925362"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY